---
apiVersion: v1
kind: Namespace
metadata:
  name: cosmic-debug-agent
# Deployment definition
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmic-debug-agent-dev
  namespace: cosmic-debug-agent
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent-container
        image: nginx:latest
        ports:
        - containerPort: 80
