apiVersion: v1
kind: Namespace
metadata:
  name: cosmic-managementplane-nightwatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nightwatch-executor
  namespace: cosmic-managementplane-nightwatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nightwatch-controller-contributor
  namespace: cosmic-managementplane-nightwatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nightwatch-controller-contributor
subjects:
- kind: ServiceAccount
  name: nightwatch-controller
  namespace: cosmic-nightwatch-controller