---
apiVersion: v1
kind: Namespace
metadata:
  name: cosmic-nightwatch-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nightwatch-controller
  namespace: cosmic-nightwatch-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    version: {{BUILD_VERSION}}
  name: elect-nightwatch-controller-leader
  namespace: cosmic-nightwatch-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-election-member
subjects:
- kind: ServiceAccount
  name: nightwatch-controller
  namespace: cosmic-nightwatch-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    version: {{BUILD_VERSION}}
  name: nightwatch-controller-viewer
rules:
- apiGroups:
  - office.com
  resources:
  - nightwatches
  verbs:
  - list
  - watch
- apiGroups:
  - office.com
  resources:
  - nightwatchdeployments
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    version: {{BUILD_VERSION}}
  name: nightwatch-controller-contributor
rules:
- apiGroups:
  - office.com
  resources:
  - nightwatches
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - office.com
  resources:
  - nightwatchdeployments
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nightwatch-controller-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nightwatch-controller-viewer
subjects:
- kind: ServiceAccount
  name: nightwatch-controller
  namespace: cosmic-nightwatch-controller  