---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.9.3
  name: keda
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.9.3
  name: keda-operator
  namespace: keda
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-auth-reader
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.9.3
  name: keda-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-hpa-controller-external-metrics
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.9.3
  name: keda-hpa-controller-external-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system